### ISSUE TITLE
example:twitter-hashtag wrapping error

### ISSUE THREAD

**Issue by MrGJones** [pimoroni/scroll-phat-hd#40] opened 2017-11-12 22:23 UTC
there appears to be a wrapping error.

after the scrolling tweet has completed, the '>>>>>' from the beginning of the string is wrapped and then gets cleared from the scrollphat. seems to be some buffer length problem?

**Comment by Gadgetoid** [comment] 2017-11-13 21:04
I think I came across this when I was modifying the example for something else actually, the issue is that `status_length` is the total length of the string in pixels, rather than the total amount of pixels it needs to be scrolled to fully slide across the display.

It needs rewritten to:

* Subtract the width of Scroll pHAT HD from `status_length`
* Pause for a second when first showing the text
* Scroll as normal
* Pause for a second at the last point in scrolling
* Clear

But for now you can probably do something like:

```python
status_length -= scrollphathd.width
```

I think it also needs one more pixel lopped off, so it might have to be:

```python
status_length = status_length - scrollphathd.width - 1
```

**Comment by MrGJones** [comment] 2017-11-13 21:22
Ok thanks Phil. I'm sure it used to be Ok? Has something changed in the
library?

**Comment by MrGJones** [comment] 2017-11-13 23:37
phil we had a similar problem during earlier stages of this and it was
fixed in your development branch! (somehow) :)
https://forums.pimoroni.com/t/porting-scrollphat-to-scrollphat-hd/4431/11

**Comment by MrGJones** [comment] 2017-11-15 08:54
@Gadgetoid hey phil i've just run this on the old rpi with this dev build on it and it works ok on there.

**Comment by Gadgetoid** [comment] 2017-11-21 14:27
But the devel branch was merged into master back in April, so that's pretty ancient history.

I can't see what's broken it, but it should be easy enough to update and fix, with a couple of timing tweaks too.

For my ScrollBot web API I used the following variation:

```python
    while running:
        try:
            scrollphathd.clear()
            status = q.get(False)
            scrollphathd.write_string(status,font=font5x7, brightness=0.1)
            status_length = scrollphathd.write_string(status, x=0, y=0, font=font5x7, brightness=0.1) - scrollphathd.width - 1

            # Show string at start
            scrollphathd.show()

            # Pause for a second
            time.sleep(1)

            # Scroll through the string
            while status_length > 0:
                scrollphathd.scroll(1)
                scrollphathd.show()
                status_length -= 1
                time.sleep(0.02)

            # Pause again at the end
            time.sleep(1)

            # Clear the display
            scrollphathd.clear()
            scrollphathd.show()

            q.task_done()

        except queue.Empty:
            time.sleep(1)
```

This pauses at the beginning/end of the scrolling message, too, to make it less jarring.

**Comment by MrGJones** [comment] 2017-11-22 08:05
Hi phil thanks for the reply mate..i need to check the code again as I've
been tinkering with versions of the btc ticker and aiy again lately 😁

**Comment by Gadgetoid** [comment] 2018-01-23 11:56
Ahoy @MrGJones - did you have an opportunity to look into this?

**Comment by MrGJones** [comment] 2018-01-23 12:06
Not yet mate, too much graphics work lately I'm afraid.. but it's still on
my list to do.

**Comment by MrGJones** [comment] 2018-11-22 15:12
just soldered up and another scrollpHAT HD so I thought I'd revisit this to work out the problem but it appears something else has b0rked it entirely, does this script work for anyone at all? :)

**Comment by MrGJones** [comment] 2018-11-25 11:30
@Gadgetoid hey phil, i've tested this and all seems ok now? so you can del this case i think!

 on another note it appears the tweets being fetched by tweepy are being truncated to 140chars so i need to look into this "extended_tweet" function: https://developer.twitter.com/en/docs/tweets/tweet-updates

**Closed** 2019-08-29 14:46 UTC
Labels: bug
