### ISSUE TITLE
90 and 270 degree rotations don't work properly.

### ISSUE THREAD

**Issue by ali1234** [pimoroni/scroll-phat-hd#5] opened 2017-03-03 21:51 UTC
Seems that the display is still treated as 7 pixels high and 17 wide.

Test case:

```
#!/usr/bin/env python

import time
import signal
import math

import scrollphathd
from scrollphathd.fonts import font5x5


while True:
    str_hours = time.strftime("%H")
    scrollphathd.rotate(90) # or 270
    scrollphathd.clear()
    scrollphathd.write_string(str_hours, x=0, y=0, font=font5x5, brightness=0.02)
    scrollphathd.show()
    time.sleep(0.1)
```

**Comment by Gadgetoid** [comment] 2017-03-07 19:13
I'd hypothesise that the problem is somewhere in the `show` method since I've purposefully avoided any in-place modifications to the buffer- it's *only* rotated/flipped/scrolled etc when it's displayed.

The actual buffer size/shape is arbitrary- it will grow as you fill it.

My fix would be to move the buffer cropping down to *after* the rotate transformation is applied, like so:

```python
        if self._rotate:
            display_buffer = numpy.rot90(display_buffer, self._rotate)

        # Chop a width * height window out of the display buffer
        display_buffer = display_buffer[:self.width, :self.height]
```
This should have the desired effect of producing a correctly rotated and cropped buffer, which is then flipped. Flipping happens after cropping, otherwise you end up showing the other end of the buffer, rather than just flipping the contents of the display aperture.

**Comment by ali1234** [comment] 2017-03-07 19:16
That's what my pull request does... among other things. :)

**Comment by Gadgetoid** [comment] 2017-03-07 19:16
Hmm, this introduces another bug. Since it's rotated before its cropped, the crop ends up being the wrong end of the buffer.

I wonder if simply a buffer of width/height `max(self.width, self.height)` would work.

**Comment by Gadgetoid** [comment] 2017-03-07 19:22
Okay it does work, but flipping along the x axis causes a problem where the 17x17 buffer is clipped on the right side instead of the left. Needs some more thought, I think.

**Comment by ali1234** [comment] 2017-03-07 20:00
I didn't realize the buffer can change size. I would have expected an explicit reshape(x,y) function, for clear() to not reset the buffer size, and for the font renderer to have a function that returns the space needed for a given string and font. Not seeing any of those things I assumed that draws outside the buffer were just discarded, as is normal for... just about every graphics library ever :)

**Comment by ali1234** [comment] 2017-03-07 20:06
So given the arbitrary sized buffer, doing the rotation in place is indeed wrong. It just means that crop needs to take into account the rotation. Flipping should still be done after the crop, so no problem there.

**Comment by ali1234** [comment] 2017-03-07 20:32
So here the crop is done before the rotate, but the x,y arguments are flipped based on the current rotation.

**Comment by ali1234** [comment] 2017-03-10 18:50
Hang on a minute. I just realised that's dumb. width == height anyway now, so reversing them does nothing. width and height should always refer to the physical size of the display, and the initial buffer creation should be done to max(width, height) in both directions as you said.

**Comment by Gadgetoid** [comment] 2017-03-13 09:27
Aye, that's correct. I'll test your PR and get it merged today.

The buffer not mapping 1:1 to the display is definitely unusual- I'll grant you that- but it makes it much easier to scroll/pan stuff without having to work out lots of separate co-ordinates and re-draw every frame :D

**Closed** 2017-04-12 11:43 UTC
Labels: bug, enhancement
